server:
    port: 8081   # web\u5E94\u7528\u670D\u52A1\u7AEF\u53E3

spring:
    redis:
        #redis数据库地址
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 1000

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/xlgTask?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

    kafka:
        bootstrap-servers: localhost:9092 #这个是你server.properties中配置的
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group-id: spring-kafka-test-group #这个去config/consumer.properties中查看和修改
        listener:
            ack-mode: manual